# Workflow that runs Node.js tests on a repository
# TODO: Cache code for faster build times and type processing.
name: Node.js test runner

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: "npm ci"
      - name: Build project
        run: "npm run build"
      - name: Run tests
        run: "npm test"